name: actionlint

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/**
      - aqua/actionlint.yaml
  push:
    branches:
      - main
    paths:
      - .github/**
      - aqua/actionlint.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 # v2
      - uses: aquaproj/aqua-installer@7c7338067bdb97d5bea2acc82b5870afca470d18 # v2.3.0
        with:
          aqua_version: v2.24.1
      - run: actionlint
