name: actionlint

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/**
      - aqua/actionlint.yaml
  push:
    branches:
      - main
    paths:
      - .github/**
      - aqua/actionlint.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aquaproj/aqua-installer@v1.2.0
        with:
          aqua_version: v1.30.1
      - run: actionlint
