name: actionlint

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/**
      - aqua/actionlint.yaml
  push:
    branches:
      - main
    paths:
      - .github/**
      - aqua/actionlint.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 # v2
      - uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
        with:
          aqua_version: v2.27.3
      - run: actionlint
