name: actionlint

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/**
      - aqua/actionlint.yaml
  push:
    branches:
      - main
    paths:
      - .github/**
      - aqua/actionlint.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aquaproj/aqua-installer@a39f721a15ed34ccbc85706e6e8ae8572c9ca9c6 # v1.2.0
        with:
          aqua_version: v1.32.0
      - run: actionlint
